[flags]
memory_legend = "top-left"
network_legend = "top-left"
default_widget_type = "proc"
tree = true
hide_time = true
# basic = true

[processes]
columns = ["PID", "Name", "CPU%", "Mem%", "User"]

[[row]]
  [[row.child]]
    [[row.child.child]]
      ratio=4
      type="cpu"
    [[row.child.child]]
      ratio=3
      type="mem"
    [[row.child.child]]
      ratio=3
      type="net"
    [[row.child.child]]
      ratio=3
      type="temp"
  [[row.child]]
    type="proc"
